package org.dynjs.ir;

public enum Operation {
    BEQ, COPY, LT, JUMP, LE, MUL, LABEL, RETURN, CALL, PROPERTY_LOOKUP, THROW_EXCEPTION,
    EXCEPTION_REGION_END, EXCEPTION_REGION_START, DEFINE_FUNCTION, ADD
}
